name: Build php image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: build tags
        type: choice
        options:
          - develop
          - latest
        required: true
        default: develop

env:
  DOCKER_USER: foxsystem

jobs:
  build-docker:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: $DOCKER_USER
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Setup
        uses: docker/setup-buildx-action@v3

      - name: Build fpm
        uses: docker/build-push-action@v3
        with:
          context: ./builder
          platforms: linux/amd64,linux/arm64
          file: ./builder/backend-apt.Dockerfile
          push: true
          target: fpm
          tags: $DOCKER_USER/php:fpm

      - name: Build swoole
        uses: docker/build-push-action@v3
        with:
          context: ./builder
          platforms: linux/amd64,linux/arm64
          file: ./builder/backend-apt.Dockerfile
          push: true
          target: swoole
          tags: $DOCKER_USER/php:swoole